fix: get count of all reports when no filter is applied
whamester/WMDD-4885-Project pull request #125
Opened 2023-11-18 17:59 UTC by BryanCaldeira

2023-11-18 18:00 UTC, BryanCaldeira commented on assets/models/Map.js
> +
when no filter is applied, this gets the count of the markers on the map - only hazard markers

2023-11-18 18:02 UTC, BryanCaldeira commented on pages/home/script.js
>      hazardShowCount = geoMap.filterMarkerCount(hazardTempFilters);
This logic was no longer needed as we show `all reports` when `hazardTempFilters` array has no id's in it.

2023-11-18 19:35 UTC, ReinhardtBotha approved these changes

2023-11-18 21:25 UTC, whamester commented
Clear the filters:
- This should be a two-step action: clear the filters and then apply the changes.
 - Clicking the `Clear All` should clear the selected checkboxes and display the count of the `Show # reports` button, by clicking on `Show # reports` is when the filters are applied on the map.

Styles:
- Double-check the styles of the filters, the typography, spacing, and colors should match the designs

2023-11-18 21:27 UTC, whamester requested changes
Clear the filters: This should be a two-step action: clear the filters and then apply the changes.

- Clicking the Clear All should clear the selected checkboxes and display the count of the Show # reports button, by clicking on Show # reports is when the filters are applied on the map.


Styles:

Double-check the styles of the filters, the typography, spacing, and colors should match the designs

2023-11-22 01:15 UTC, whamester approved these changes

2023-11-22 01:16 UTC, merged