feat: show recent reports which are active
whamester/WMDD-4885-Project pull request #126
Opened 2023-11-18 18:26 UTC by BryanCaldeira

Trello Card
[163-view-hazards-display-only-the-recent-and-ongoing-hazards](https://trello.com/c/N3oXFKuF/163-view-hazards-display-only-the-recent-and-ongoing-hazards)

- Addition changes made on lat, lng change only when user has moved more than 25Km's from current position

2023-11-18 18:27 UTC, BryanCaldeira commented on pages/home/script.js
>  };
If user's location has changed and has a difference of more than 25Km's considering we are fetching reports for a 50Km's  area.

2023-11-18 18:28 UTC, BryanCaldeira commented on pages/home/script.js
Active and recent reports only

2023-11-18 19:39 UTC, ReinhardtBotha approved these changes

2023-11-18 21:30 UTC, whamester requested changes

2023-11-18 21:30 UTC, whamester commented on pages/home/script.js
> +  const url = `hazard-report?cursor=${cursor}&size=${size}&lat=${
remove the cursor and size from the request, since these params are disabled in the backend we don't need them.

2023-11-20 17:16 UTC, whamester approved these changes

2023-11-20 17:16 UTC, merged